name: Update README with Recent Activity

on:
  schedule:
    - cron: '0 */6 * * *'  # Updates every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update Profile README
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate GitHub Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update recent activity'
          MAX_LINES: 5
          COMMIT_NAME: 'github-actions[bot]'